---
- name: Install my site
  become: yes
  hosts: all

  roles:
    - test-role
    - nodejs
  #  - mongodb
  #  - mongodbcreat
    - nginxdefault    
  #  - phpinstall
  #  - test-php
  #  - adminer
  #  - siteinstall
    - rsyncinstall
    - server
  #  - adminer2
  #  - pm2
  #  - pm2-
  #  - client #camera.html
    # - phpmyadmin
    #- letsencrypt
